In [1]:
import numpy as np
import pandas as pd
from google.colab import files
import io
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error, r2_score
from sklearn import preprocessing
import matplotlib.pyplot as plt
import copy, math
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('students.csv')
df

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [3]:
df = df.dropna()
df.shape

(4424, 35)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance                      4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Nacionality                                     4424 non-null   int64  
 7   Mother's qualification                          4424 non-null   int64  
 8   Father's qualification                          4424 non-null   int64  
 9   Mother's occupation                      

In [5]:
df['Target'].unique()

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

In [6]:
df['Target'] = df['Target'].replace('Dropout', 'non-Graduate')
df['Target'] = df['Target'].replace('Enrolled', 'non-Graduate')
df['Target'].unique()

array(['non-Graduate', 'Graduate'], dtype=object)

In [7]:
encoder = LabelEncoder()
encoder.fit(df['Target'])
df['Target'] = encoder.transform(df['Target'])
df['Target'].unique()

array([1, 0])

In [8]:
dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))

{'Graduate': 0, 'non-Graduate': 1}

In [9]:
X = df.iloc[:,:-1].values
print(f'X shape: {X.shape}, type: {type(X)} \n')
X

X shape: (4424, 34), type: <class 'numpy.ndarray'> 



array([[ 1.  ,  8.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       [ 1.  ,  6.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  1.  , ...,  9.4 , -0.8 , -3.12],
       [ 1.  ,  5.  ,  1.  , ..., 12.7 ,  3.7 , -1.7 ]])

In [10]:
y = df['Target'].values
print(f'X shape: {y.shape}, type: {type(y)} \n')
y

X shape: (4424,), type: <class 'numpy.ndarray'> 



array([1, 0, 1, ..., 1, 0, 0])

In [11]:
scaler = StandardScaler()

scaler.fit(X)
X_scaled = scaler.transform(X)
print(f'X shape: {X.shape}, type: {type(X)} \n')
X

X shape: (4424, 34), type: <class 'numpy.ndarray'> 



array([[ 1.  ,  8.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       [ 1.  ,  6.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  1.  , ...,  9.4 , -0.8 , -3.12],
       [ 1.  ,  5.  ,  1.  , ..., 12.7 ,  3.7 , -1.7 ]])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.33, random_state=42)

In [13]:
logistic_reg_model = LogisticRegression()
logistic_reg_model.fit(X_train, y_train)

weights = logistic_reg_model.coef_
bias = logistic_reg_model.intercept_
print(f'best weights: {weights} \nbest bias: {bias}')

best weights: [[-0.15171215  0.10000492 -0.03537136  0.29946242  0.00335001 -0.08791031
  -0.04590712 -0.07711034 -0.12475809 -0.09188389  0.08143744  0.0469557
   0.01365519  0.2837385  -0.68168065  0.12380069 -0.31294379  0.21469302
  -0.09224394  0.31316431  0.72977434  0.16414803 -2.1010678   0.45736779
  -0.09133405  0.11352192  1.47037488  0.45255216 -2.68827154 -0.68660221
  -0.20246141  0.06581675 -0.00651889 -0.02399549]] 
best bias: [0.93369145]


In [14]:
y_pred = logistic_reg_model.predict(X_test)

for i in range(100):
  print(f'Label: {y_test[i]:<10} | Prediction: {y_pred[i]:<10}')

Label: 1          | Prediction: 1         
Label: 0          | Prediction: 0         
Label: 0          | Prediction: 0         
Label: 0          | Prediction: 0         
Label: 1          | Prediction: 1         
Label: 0          | Prediction: 1         
Label: 1          | Prediction: 0         
Label: 1          | Prediction: 0         
Label: 0          | Prediction: 0         
Label: 0          | Prediction: 0         
Label: 0          | Prediction: 1         
Label: 0          | Prediction: 0         
Label: 1          | Prediction: 1         
Label: 0          | Prediction: 0         
Label: 1          | Prediction: 0         
Label: 1          | Prediction: 0         
Label: 1          | Prediction: 0         
Label: 0          | Prediction: 0         
Label: 1          | Prediction: 1         
Label: 0          | Prediction: 0         
Label: 0          | Prediction: 0         
Label: 1          | Prediction: 1         
Label: 1          | Prediction: 1         
Label: 0   

In [17]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.836986301369863

**Compare to manual Logistic Regression** <br>

manual Logistic Regression: accuracy = 0.5