In [1]:
import numpy as np
import pandas as pd
from google.colab import files
import io
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error, r2_score
from sklearn import preprocessing
import matplotlib.pyplot as plt
import copy, math
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [14]:
df = pd.read_csv('students.csv')
df

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [17]:
df = df.dropna()
df.shape

(4424, 35)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance                      4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Nacionality                                     4424 non-null   int64  
 7   Mother's qualification                          4424 non-null   int64  
 8   Father's qualification                          4424 non-null   int64  
 9   Mother's occupation                      

In [19]:
df['Target'].unique()

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

In [20]:
encoder = LabelEncoder()

df['Target'] = encoder.fit_transform(df['Target'])
df['Target'].unique()

array([0, 2, 1])

In [27]:
dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))

{'Dropout': 0, 'Enrolled': 1, 'Graduate': 2}

In [28]:
X = df.iloc[:,:-1].values
print(f'X shape: {X.shape}, type: {type(X)}')
X

X shape: (4424, 34), type: <class 'numpy.ndarray'>


array([[ 1.  ,  8.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       [ 1.  ,  6.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  1.  , ...,  9.4 , -0.8 , -3.12],
       [ 1.  ,  5.  ,  1.  , ..., 12.7 ,  3.7 , -1.7 ]])

In [29]:
y = df.iloc[:,-1].values
print(f'y shape: {y.shape}, type: {type(y)}')
y

y shape: (4424,), type: <class 'numpy.ndarray'>


array([0, 2, 0, ..., 0, 2, 2])

In [30]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
print(f'X shape: {X_scaled.shape}, type: {type(X_scaled)}')
X_scaled

X shape: (4424, 34), type: <class 'numpy.ndarray'>


array([[-0.29482875,  0.21006857,  2.49089589, ..., -0.28763846,
         0.12438647,  0.76576084],
       [-0.29482875, -0.16740639, -0.55406775, ...,  0.87622207,
        -1.10522155,  0.34719942],
       [-0.29482875, -1.11109377,  2.49089589, ..., -0.28763846,
         0.12438647,  0.76576084],
       ...,
       [-0.29482875, -1.11109377, -0.55406775, ...,  0.87622207,
        -1.10522155,  0.34719942],
       [-0.29482875, -1.11109377, -0.55406775, ..., -0.81325289,
        -1.46687097, -1.37551124],
       [-0.29482875, -0.35614386, -0.55406775, ...,  0.42569541,
         1.7879738 , -0.74987207]])

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.33, random_state=42)

In [40]:
logistic_reg_model = LogisticRegression(multi_class='multinomial', solver='lbfgs')
logistic_reg_model.fit(X_train, y_train)

weights = logistic_reg_model.coef_
bias = logistic_reg_model.intercept_
print(f'best weights: {weights} \nbest bias: {bias}')

best weights: [[-7.43852147e-02  1.58683012e-02  4.34261974e-02  2.89369835e-01
   3.19654170e-02 -1.77584529e-02  1.05840600e-01  1.13485509e-01
  -6.78596964e-02 -2.42706432e-01 -1.99559898e-02  8.68304581e-02
  -2.18658618e-02  1.43107332e-01 -5.13445577e-01  9.13423108e-02
  -9.32267476e-02  3.04680174e-01 -2.05421680e-01  1.60229085e-01
   3.50325726e-01 -6.14788611e-02 -9.10986717e-01  2.87237693e-01
  -2.44369000e-02  2.83589739e-01  8.56486113e-01 -3.57087142e-02
  -1.52992752e+00 -4.98772221e-01 -8.36493822e-02  1.45841094e-01
   1.07319637e-02  2.94766855e-02]
 [-3.04701964e-02  5.38757503e-02 -5.49686195e-02 -5.91822083e-02
  -3.29957124e-02 -3.61956058e-02 -8.90731352e-02 -1.37495814e-01
  -1.49905672e-02  1.32049989e-01  4.48366263e-02 -4.28758901e-02
   2.53225292e-02  5.10754224e-02  6.04972572e-02  2.66787112e-04
  -1.08742911e-01 -1.45316333e-01  8.71088343e-02  5.38592151e-02
   1.55410431e-01  1.54197495e-01 -5.42241798e-01  4.50349810e-02
  -4.37728454e-02 -2.064261

In [44]:
y_pred = logistic_reg_model.predict(X_test)

for i in range(50):
  print(f'Label: {y_test[i]:<10} | Prediction: {y_pred[i]:<10}')

Label: 0          | Prediction: 0         
Label: 2          | Prediction: 2         
Label: 2          | Prediction: 2         
Label: 2          | Prediction: 2         
Label: 0          | Prediction: 0         
Label: 2          | Prediction: 1         
Label: 1          | Prediction: 2         
Label: 0          | Prediction: 2         
Label: 2          | Prediction: 2         
Label: 2          | Prediction: 2         
Label: 2          | Prediction: 1         
Label: 2          | Prediction: 2         
Label: 0          | Prediction: 0         
Label: 2          | Prediction: 2         
Label: 0          | Prediction: 2         
Label: 1          | Prediction: 2         
Label: 1          | Prediction: 2         
Label: 2          | Prediction: 2         
Label: 1          | Prediction: 0         
Label: 2          | Prediction: 2         
Label: 2          | Prediction: 2         
Label: 0          | Prediction: 0         
Label: 0          | Prediction: 0         
Label: 2   

In [45]:
accurracy = accuracy_score(y_test, y_pred)
accurracy

0.7534246575342466